apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: files-trigger
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: spacy
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /files
    tls: ""
  method: POST
  relativeurl: /files


# export FISSION_ROUTER=10.99.196.34:31314