# This whale shows off a basic workflow that combines both Fission Functions (fortune, whalesay) and internal functions (noop)
apiVersion: 1
output: OutputAggregator
tasks:
  FileDistributor:
    run: noop

  NEROperator:
    run: fortune
    requires:
    - FileDistributor

  OutputAggregator:
    run: whalesay
    inputs: "{$.Tasks.NEROperator.Output}"
    requires:
    - NEROperator



    