include:
- sentiment/*
kind: ArchiveUploadSpec
name: sentiment-KVCj

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: sentiment-b807efcd-fb58-4c40-b366-87f6dcb8c1f4
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sentiment-KVCj
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-01-03T22:32:32.553961Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: sentiment
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  package:
    functionName: sentiment.main
    packageref:
      name: sentiment-b807efcd-fb58-4c40-b366-87f6dcb8c1f4
      namespace: default
  resources: {}
  secrets: null
